spring:
  application:
    name: ${vcap.application.application_name:}

  security:
    user:
      name: ${ADMIN_ID:admin}
      password: ${ADMIN_PWD:admin}

  boot:
    admin:
      ui:
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span> ${vcap.application.application_name:Spring Boot Admin} </span>
        title: ${vcap.application.application_name:Spring Boot Admin}
      notify:
        slack:
          webhook-url: ${SLACK_WEBHOOK:}
          channel: ${SLACK_CHANNEL}
          username: ${SLACK_USERNAME}